Zeag energie
mobidata-bw/x2gbfs pull request #173
Opened 2024-10-18 09:45 UTC by ThorstenFroehlinghaus

new MOQO feed

2024-10-19 14:28 UTC, hbruch requested changes
I suggest to get rid of the currently needless provider specific subclasses.

And depending on the expected address properties, it might be appropriate to be a bit more defensive in accessing them.

Be aware, that the GBFS spec defines `address` as:

> 
Address (street number and name) where station is located. This MUST be a valid address, not a free-form text description. Example: 1234 Main Street

While currently no `city`, but just a `post_code` attribute is defined, I added only the city to the address, and provided the postal code via `post_code`.

2024-10-19 14:28 UTC, hbruch commented on x2gbfs/providers/moqo.py
> +    pass
As long as the superclass' default behavior is sufficient, you even would not need to define a subclass. For now, we could get rid of `StadtwerkTauberfrankenProvider`and `ZeagEnergieProvider` and just use `MoqoProvider`

2024-10-19 14:28 UTC, hbruch commented on x2gbfs/x2gbfs.py
> +    ZeagEnergieProvider,
I suggest to switch to `MoqoProvider`

2024-10-19 14:28 UTC, hbruch commented on x2gbfs/x2gbfs.py
> +        return ZeagEnergieProvider(feed_config)
Here as well

2024-10-21 05:43 UTC, ThorstenFroehlinghaus commented
Ok, I removed the subclasses and changed the address format.

2024-10-21 06:27 UTC, hbruch approved these changes
LGTM

2024-10-21 06:30 UTC, merged